apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: default
patches:
  - target:
      kind: Deployment
      name: k8s-mcp
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: 15s
